apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sujithafrontend
  namespace: suwetha-ns 
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: su-app
  template:
    metadata:
      labels:
        app: su-app
    spec:
      containers:
      - name: register-image 
        image: suwetha07/registerimage:v1.1.0
        ports:
         - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sujithaservice
  namespace: suwetha-ns 
spec:
  selector:
    app: su-app
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 3000
  type: NodePort    

         